### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by Qqwy** [Dimagog/persistent_vector#1]
Hi there!

I think that persistent vectors are a great concept, and that they should receive more widespread attention within the Elixir community.

What are your plans with this library? I am currently working on [Arrays](https://github.com/Qqwy/elixir-arrays/) and would love to add a persistent vector-backed array implementation in one way or the other.

One option would be to add PersistentVector to it, making it become part of the Arrays library. 

Or if you'd rather like `persistent_vector` to remain its own library, that's also possible. I could contribute here with adding documentation, some tests, and the bare minimum to allow `persistent_vector` to be used with Arrays (i.e. implementing the Arrays.Behaviour [`empty/1`](https://hexdocs.pm/arrays/Arrays.Behaviour.html#c:empty/1) callback, and separately the `Arrays.Protocol`).

What do you think? :slightly_smiling_face: 

Have a wonderful day,

~Marten/Qqwy

**Comment by Dimagog** [comment]
Hi Marten,
I need this library to remain stand-alone and with no dependencies.
Can you simply refer users of your library to this one and conditionally implement required protocols when it’s present?

**Comment by Qqwy** [comment]
Yes, of course!

I will add `:persistent_vector` as an optional dependency to `:arrays`, and implement the `Arrays.Protocol` for it there.
To finish the integration, I will try to write efficient implementations for:

- Reducing right-to-left (besides the already supported left-to-right)
- Mapping a function over all elements, resulting in a new PersistentVector
- Resizing the array (filling it with a default value when becoming larger, and chopping off the elements at the end when becoming smaller)
- Returning a contiguous subsequence as a slice (either as another PersistentVector or as a list).

and I will share those implementations as PRs here for inclusion in PersistentVector itself.

:green_heart: 

Great work on this library! My preliminary benchmarking shows that it is still much faster than maps and `:array`, even on Elixir 1.12 runing on OTP24, which has had many optimization improvements related to maps and tuples since the last benchmark you've done.

**Comment by Qqwy** [comment]
Note: I have decided to instead focus on/integrate with the library [Aja](https://github.com/sabiwara/aja) as it seems to be more mature and more actively maintained.
Thank you for your time!
